In [10]:
import numpy as np
# .dot(x) 与x相乘
# X.T 转置
# np.linalg.inv() 逆矩阵

$W = (X^TX)^{-1}X^Ty$

$\begin{cases}
x + y=14\\  2x - y = 10\\
\end{cases}
\\\\
\begin{cases}
x - y + z = 100\\ 2x + y -z = 80\\ 3x - 2y + 6z = 256\\
\end{cases}
\\\\
\left\{\begin{align}&14x_2 + 8x_3 + 5x_5 + -2x_6 + 9x_7 + -3x_8 = 339\\&-4x_1 + 10x_2 + 6x_3 + 4x_4 + -14x_5 + -2x_6 + -14x_7 + 8x_8 = -114\\&-1x_1 + -6x_2 + 5x_3 + -12x_4 + 3x_5 + -3x_6 + 2x_7 + -2x_8 = 30\\&5x_1 + -2x_2 + 3x_3 + 10x_4 + 5x_5 + 11x_6 + 4x_7 + -8x_8 = 126\\&-15x_1 + -15x_2 + -8x_3 + -15x_4 + 7x_5 + -4x_6 + -12x_7 + 2x_8 = -395\\&11x_1 + -10x_2 + -2x_3 + 4x_4 + 3x_5 + -9x_6 + -6x_7 + 7x_8 = -87\\&-14x_1 + 4x_3 + -3x_4 + 5x_5 + 10x_6 + 13x_7 + 7x_8 = 422\\&-3x_1 + -7x_2 + -2x_3 + -8x_4 + -6x_6 + -5x_7 + -9x_8 = -309\end{align}\right.
$

In [14]:
X = np.array(object=[[1, 1], [2, -1]])
y = np.array(object=[14, 10])

np.linalg.inv(X.T.dot(X)).dot(X.T.dot(y))

array([8., 6.])

In [12]:
X = np.array(object=[
    [1, -1, 1],
    [2, 1, -1],
    [3, -2, 6]
])
y = np.array(object=[100, 80, 256])

np.linalg.inv(X.T.dot(X)).dot(X.T.dot(y))

array([ 60., -41.,  -1.])

In [15]:
X = np.array([
    [0, 14, 8, 0, 5, -2, 9, -3],
    [-4, 10, 6, 4, -14, -2, -14, 8],
    [-1, -6, 5, -12, 3, -3, 2, -2],
    [5, -2, 3, 10, 5, 11, 4, -8],
    [-15, -15, -8, -15, 7, -4, -12, 2],
    [11, -10, -2, 4, 3, -9, -6, 7],
    [-14, 0, 4, -3, 5, 10, 13, 7],
    [-3, -7, -2, -8, 0, -6, -5, -9]
])
# 对应的y
y = np.array([339, -114, 30, 126, -395, -87, 422, -309])

np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])