In [1]:
import numpy as np 

In [5]:
np.linspace(0, 100, 10, endpoint=True) # 将0-100 均分为10份
np.arange(0, 100, 20) # 元素从0开始，步长为20，最后一个元素不超过100

array([ 0, 20, 40, 60, 80])

In [29]:
a = np.random.randint(0, 100, size=(3,4))
np.argmax(a).reshape(3,-1)

ValueError: cannot reshape array of size 1 into shape (3,newaxis)

In [35]:
a = np.random.randint(0, 100, size=(3,4))
print(a)
a.argmin()



[[65 77  3  0]
 [77  6 52 85]
 [70  2 76 91]]


NameError: name 'arr' is not defined